name: Deploy the React app on AWS S3
on:
  push:
    branches: ['stage']

permissions:
  id-token: write
  contents: read

env:
  environment: stage

jobs:
  deploy-website:
    name: Run cloudformation to deploy s3 and cloudfront configuration
    uses: ./.github/workflows/main.yml
    with:
      environment: ${environment}
    secrets:
      AWS_GITHUB_ROLE: ${{ secrets.AWS_GITHUB_ROLE }}
