name: Deploy the React app on AWS S3
on:
  push:
    branches: ['stage']

permissions:
  id-token: write
  contents: read

jobs:
  deploy-website:
    name: Run cloudformation to deploy s3 and cloudfront configuration
    uses: ./.github/workflows/main.yml
    with:
      environment: stage

    secrets:
      AWS_GITHUB_ROLE: ${{ secrets.AWS_GITHUB_ROLE }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
